/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Quote = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllJokes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getJoke' : IDL.Func([IDL.Nat], [Quote], ['query']),
  'getTotalJokes' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Quote = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'getAllJokes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getJoke' : IDL.Func([IDL.Nat], [Quote], ['query']),
    'getTotalJokes' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };